options:
  machineType: "N1_HIGHCPU_8"
timeout: 7200s
steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - buildx
      - build
      - "--progress=plain"
      - "--file=docker/tilemaker-debian.Dockerfile"
      - "--tag=test"
      - .
