name: Build all Docker images
on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  PLATFORMS: linux/amd64
  #PLATFORMS: linux/amd64,linux/arm64

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.result.outputs.tag }}
    steps:
      - name: get latest tag
        id: result
        run: curl -s https://api.github.com/repos/versatiles-org/versatiles-rs/tags | jq -r '"tag=" + first(.[] | .name | select(startswith("v")))' >> "$GITHUB_OUTPUT"

  alpine:
    needs: [init]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      name: alpine
      platforms: "${{ env.PLATFORMS }}"
      tag: "${{ needs.init.outputs.tag }}"

  scratch:
    needs: [init]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      name: scratch
      platforms: "${{ env.PLATFORMS }}"
      tag: "${{ needs.init.outputs.tag }}"

  debian:
    needs: [init]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      name: debian
      platforms: "${{ env.PLATFORMS }}"
      tag: "${{ needs.init.outputs.tag }}"

  debian-frontend:
    needs: [init, debian]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      name: debian-frontend
      platforms: "${{ env.PLATFORMS }}"
      tag: "${{ needs.init.outputs.tag }}"
