name: Build all Docker images
on:
  repository_dispatch:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.result.outputs.tag }}
    steps:
      - name: get latest tag
        id: result
        run: curl -s https://api.github.com/repos/versatiles-org/versatiles-rs/tags | jq -r '"tag=" + first(.[] | .name | select(startswith("v")))' >> "$GITHUB_OUTPUT"

  alpine-arm:
    needs: [init]
    uses: versatiles-org/versatiles-docker/.github/workflows/build-single-image.yml@main
    secrets: inherit
    with: { name: alpine, platform: linux/arm64, tag: ${{ needs.init.outputs.tag }} }



#  alpine-arm2:
#    needs: [init]
#    strategy:
#      matrix:
#        name: [debian, alpine, scratch]
#        platform: [linux/amd64, linux/arm64]
#    uses: versatiles-org/versatiles-docker/.github/workflows/build-single-image.yml@main
#    secrets: inherit
#    with:
#      path: docker/level1/
#      name: ${{ matrix.name }}
#      platform: ${{ matrix.platform }}
#      tag: ${{ needs.init.outputs.tag }}
#
#  release2:
#    name: Build level 2
#    needs: [init, release1]
#    permissions:
#      packages: write
#      contents: read
#    strategy:
#      matrix:
#        based_on: [debian]
#        name: [frontend]
#        #name: [maker, frontend, nginx]
#        platform: [linux/amd64, linux/arm64]
#    uses: versatiles-org/versatiles-docker/.github/workflows/build-single-image.yml@main
#    secrets: inherit
#    with:
#      path: docker/level2/
#      name: ${{ matrix.based_on }}-${{ matrix.name }}
#      platform: ${{ matrix.platform }}
#      tag: ${{ needs.init.outputs.tag }}
