name: Build all Docker images
on:
  repository_dispatch:
    inputs:
      run_jobs:
        default: "all"
  workflow_dispatch:
    inputs:
      run_jobs:
        description: "Run which image build process?"
        default: "all"
        type: choice
        options:
          - all
          - basic
          - frontend
          - tilemaker
          - tippecanoe

env:
  FORCE_COLOR: 1

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.result.outputs.tag }}
    steps:
      - name: get latest tag
        id: result
        run: curl -s https://api.github.com/repos/versatiles-org/versatiles-rs/tags | jq -r '"tag=" + first(.[] | .name | select(startswith("v")))' >> "$GITHUB_OUTPUT"

  ### BASIC IMAGES

  basic:
    name: Basic
    if: contains( fromJSON('["all", "basic", "frontend", "tilemaker"]'), github.event.inputs.run_jobs )
    needs: [init]
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        include:
          - { variants: "alpine,", filename: basic-alpine }
          - { variants: "debian", filename: basic-debian }
          - { variants: "scratch", filename: basic-scratch }
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      variants: ${{ matrix.variants }}
      filename: ${{ matrix.filename }}
      tag: ${{ needs.init.outputs.tag }}

  ### FRONTEND IMAGES

  frontend:
    name: Frontend
    if: contains( fromJSON('["all", "frontend"]'), github.event.inputs.run_jobs )
    needs: [init, basic]
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        include:
          - { variants: "alpine,", filename: frontend-alpine }
          - { variants: "debian", filename: frontend-debian }
          - { variants: "scratch", filename: frontend-scratch }
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      repo: versatiles-frontend
      variants: ${{ matrix.variants }}
      filename: ${{ matrix.filename }}
      tag: ${{ needs.init.outputs.tag }}

  ### TILEMAKER IMAGES

  tilemaker:
    name: Tilemaker
    if: contains( fromJSON('["all", "tilemaker"]'), github.event.inputs.run_jobs )
    needs: [init, basic]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      repo: versatiles-tilemaker
      variants: "debian,"
      filename: "tilemaker-debian"
      platforms: "linux/amd64"
      tag: ${{ needs.init.outputs.tag }}

  ### MAPLIBRE-NATIVE IMAGES

  tippecanoe:
    name: Tippecanoe
    if: contains( fromJSON('["all", "tippecanoe"]'), github.event.inputs.run_jobs )
    needs: [init]
    uses: ./.github/workflows/build-single-image.yml
    secrets: inherit
    with:
      repo: tippecanoe
      variants: "alpine,"
      filename: "tippecanoe-alpine"
      platforms: "linux/amd64"
      tag: ${{ needs.init.outputs.tag }}
